### PR TITLE
Multi receivers support for IRremote library

### PR DESCRIPTION
**Pull request by Neco777**
Hello, please review my changes and let me know if I can do anything to simplify the merge. There were some problems with my local github software so I now see 3 commits instead of 1. I do not know how to fix it - my apologizes.

### CODE REVIEW

**Comment by z3t0** [comment]
I will merge this into the experimental branch as soon as I confirm that the experimental is stable. Thanks for the contribution

**Comment by z3t0** [comment]
@Neco777 Just to help speed up the development of this library could you keep an eye out for PRs on the experimental branch and test run them

**Comment by z3t0** [comment]
@Neco777 I would really like to incorporate this into the library, if possible could you take a look ate re-basing this on #107 ? Things have been much more modularized recently. Thanks!

**Comment by SanaullahKayani** [comment]
Hy dear i am making my final year project on density base taffic signal , and i want to put 4 ir receiver in my arduino for emergency. but only one receiver works for me. its an urgent an i am too confuse, plz help

**Comment by SanaullahKayani** [comment]
i want to check which receiver receive the code that send ir transmitter. plz help me, i need 4 ir receiver in one code (arduino).

**Comment by AnalysIR** [comment]
As you may see above this was considered 5 years ago & AFAIK, it is not a standard supported feature in the library.

If you opened a new issue and provided all the suggested information requested when a new issue is opened, you may be more successful. Also, make sure to describe your project (including what you have achieved so far) as there may be an easier way to achieve what you want.

**Comment by ArminJo** [comment]
Is now documented in Readme

**Pull request closed without merging**
