### PR TITLE
Support GREE.

### PR DESCRIPTION
**Pull request by AbelHu**
1. This PR has been tested with GREE remote controller (mode: `YB0FB2`) based on the code of release v2.1.0.
2. This PR has also been tested with receiving and decoding XiaoMi and Sony remote controller.

### CODE REVIEW

**Comment by z3t0** [comment]
Would it be possible to share some documentation regarding this protocol? I would like to try and maintain a wiki of specific data regarding supported protocols.

**Comment by AbelHu** [comment]
@z3t0 This [blog](http://blog.csdn.net/yannanxiu/article/details/48174649) introduces Gree protocol in Chinese. You can translate it via google translate. [LINK](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fblog.csdn.net%2Fyannanxiu%2Farticle%2Fdetails%2F48174649&edit-text=&act=url).

**Comment by bengtmartensson** [comment]
> Would it be possible to share some documentation regarding this protocol?

[IRremote-SIL](https://github.com/bengtmartensson/IRremote-SIL) was done for testing these sort of protocols without having to flash them on an Arduino (testing on the local host instead, "SIL testing"). I made some trivial extensions for supporting the new protocol, checked in into a [branch gree](https://github.com/bengtmartensson/IRremote-SIL/tree/gree). This can be used to generate sequences that would have been sent. Some thus generated test data I feed into [IrpTransmogrifier](https://github.com/bengtmartensson/IrpTransmogrifier) (the development version), and it produced the [IRP form](http://www.hifi-remote.com/wiki/index.php?title=IRP_Notation)

    {200,msb}<3,-3|3,-8>(9000u,-4500u,A:35,3,-20m,B:32,3,-25m)

**Comment by z3t0** [comment]
@bengtmartensson thanks! that project looks like a gold mine. I'll take a look through it once I get a chance.

**Comment by AnalysIR** [comment]
I ran this thru AnalsyIR and it decodes as an Electrolux 67 bit AC signal. (It is not the relatively common GREE AC protocol.
_Don't worry about the 'name' as AC units are resold by all sorts of companies. So just treat the name as arbitrary._ 

Try the code below, in an IRremote sketch:

```
/*
Automatically Generated by AnalysIR - Batch Export Utility
Registered to: xxxxxxxx
Session History
Type : Key : Value : Bits : Carrier Frequency (kHz)
0 : ELECTROLUX67_134AC :  : 48000205200000020 : 67 : 0
1 : ELECTROLUX67_134AC :  : 4800020520004000A : 67 : 0
Note: Be sure to use the correct Carrier frequency, for each individual signal, as(or if) indicated above
*/

// NB: Not all protocols are supported by IRremote or IRLib. You may need to edit the code below manually
// Automatically Generated by AnalysIR for xxxxxxxx, visit https://www.AnalysIR.com/ or email info@....... for further details
int khz=38; //NB Change this default value as neccessary to the correct carrier frequency


unsigned int Signal_0_0[] = {8900,4400,600,1700,600,600,600,600,600,1700,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,1700,600,600,600,600,600,600,600,600,600,600,600,600,600,1700,600,600,600,1700,600,600,600,600,600,1700,600,600,600,19650,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,600,1700,600,600,600,600,600,600,600,600,600,600,600}; //AnalysIR Batch Export (IRremote) - RAW

irsend.sendRaw(Signal_0_0, sizeof(Signal_0_0)/sizeof(int), khz); //AnalysIR Batch Export (IRremote) - RAW
 // AnalysIR IR Protocol: ELECTROLUX67_134AC, Key:  


unsigned int Signal_1_1[] = {8950,4350,650,1600,650,550,650,500,650,1650,600,550,650,550,650,500,650,550,650,550,650,500,650,550,650,550,650,500,650,550,650,550,600,550,650,550,650,550,600,600,600,550,650,550,600,1650,600,600,600,550,650,550,600,600,600,550,650,550,600,1650,650,550,600,1650,600,600,600,550,650,1600,650,550,650,19700,600,600,600,550,650,550,600,600,600,550,650,550,600,600,600,550,650,550,600,600,600,550,650,550,600,600,600,1600,650,550,650,550,600,600,600,550,650,550,600,600,600,550,650,550,600,600,600,550,650,550,600,600,600,550,650,550,600,1650,600,600,600,1650,600,600,600}; //AnalysIR Batch Export (IRremote) - RAW

irsend.sendRaw(Signal_1_1, sizeof(Signal_1_1)/sizeof(int), khz); //AnalysIR Batch Export (IRremote) - RAW
 // AnalysIR IR Protocol: ELECTROLUX67_134AC, Key:  
```
Here is a trace of both your signals (click image to see more detail)
636418604659593796_analysir_screenshot

**Comment by AbelHu** [comment]
@rcanoff With this PR, the code should be similar as below.

image

**Comment by rcanoff** [comment]
@AbelHu I'm doing the following steps:
I have an AC.
I use the DumpV2 example to read the data.

then with the remote, I press the power off and get the following reading:

Encoding  : GREE
Code      : 8200040A (64 bits)
Timing[139]: 
     +8950, -4350     + 650, -1600     + 650, - 550     + 650, - 550
     + 650, - 500     + 650, - 550     + 650, - 550     + 650, -1600
     + 650, - 550     + 650, - 550     + 600, - 550     + 650, - 550
     + 650, - 550     + 600, - 550     + 650, - 550     + 650, - 550
     + 650, - 500     + 650, - 550     + 650, - 550     + 650, - 550
     + 600, - 600     + 600, - 550     + 650, -1600     + 650, - 550
     + 650, - 550     + 600, - 600     + 600, - 600     + 600, - 550
     + 600, - 600     + 600, -1650     + 650, - 550     + 600, -1650
     + 650, - 550     + 600, - 600     + 600, -1600     + 650, - 600
     + 600, -19750     + 650, -1600     + 650, - 550     + 650, - 550
     + 600, - 600     + 600, - 550     + 650, - 550     + 600, - 600
     + 600, - 550     + 650, - 550     + 600, - 600     + 600, - 600
     + 600, - 550     + 600, - 600     + 600, -1650     + 600, - 600
     + 600, - 600     + 600, - 550     + 650, - 550     + 600, - 600
     + 600, - 550     + 650, - 550     + 600, - 600     + 600, - 550
     + 650, - 550     + 600, - 600     + 600, - 550     + 650, - 550
     + 600, - 600     + 600, -1650     + 600, - 600     + 600, -1650
     + 600, -1650     + 650
unsigned int  rawData[139] = {8950,4350, 650,1600, 650,550, 650,550, 650,500, 650,550, 650,550, 650,1600, 650,550, 650,550, 600,550, 650,550, 650,550, 600,550, 650,550, 650,550, 650,500, 650,550, 650,550, 650,550, 600,600, 600,550, 650,1600, 650,550, 650,550, 600,600, 600,600, 600,550, 600,600, 600,1650, 650,550, 600,1650, 650,550, 600,600, 600,1600, 650,600, 600,19750, 650,1600, 650,550, 650,550, 600,600, 600,550, 650,550, 600,600, 600,550, 650,550, 600,600, 600,600, 600,550, 600,600, 600,1650, 600,600, 600,600, 600,550, 650,550, 600,600, 600,550, 650,550, 600,600, 600,550, 650,550, 600,600, 600,550, 650,550, 600,600, 600,1650, 600,600, 600,1650, 600,1650, 650};  // GREE 8200040A
unsigned int  data = 0x8200040A;


As it results the code 8200040A (64 bits), I then use:

irsend.sendGREE(0x8200040A, 64);
and I get the following data.

The code matches, but the raw data doesn't.

Encoding  : GREE
Code      : 8200040A (64 bits)
Timing[139]: 
     +8900, -4450     + 600, -1600     + 600, - 600     + 600, - 600
     + 600, - 600     + 600, - 550     + 650, - 600     + 600, -1550
     + 650, - 550     + 650, - 550     + 650, - 550     + 650, - 550
     + 650, - 550     + 600, - 600     + 600, - 600     + 600, - 600
     + 600, - 600     + 600, - 600     + 600, - 600     + 550, - 650
     + 600, - 550     + 650, - 550     + 600, -1600     + 600, - 600
     + 600, - 600     + 600, - 600     + 600, - 600     + 550, - 650
     + 550, - 650     + 550, -1600     + 600, - 600     + 600, -1550
     + 650, - 600     + 550, - 650     + 550, -1600     + 600, - 600
     + 600, -19800     + 600, - 600     + 600, - 600     + 600, - 600
     + 600, - 600     + 600, - 600     + 600, - 600     + 600, - 600
     + 550, - 650     + 550, - 650     + 550, - 600     + 600, - 600
     + 600, - 600     + 600, - 600     + 600, - 600     + 600, - 600
     + 600, - 600     + 600, - 600     + 600, - 600     + 600, - 600
     + 550, - 650     + 550, - 650     + 550, - 600     + 600, - 600
     + 600, - 600     + 600, - 600     + 600, -1550     + 650, - 600
     + 600, - 600     + 550, - 650     + 550, - 650     + 550, - 600
     + 600, - 600     + 600
unsigned int  rawData[139] = {8900,4450, 600,1600, 600,600, 600,600, 600,600, 600,550, 650,600, 600,1550, 650,550, 650,550, 650,550, 650,550, 650,550, 600,600, 600,600, 600,600, 600,600, 600,600, 600,600, 550,650, 600,550, 650,550, 600,1600, 600,600, 600,600, 600,600, 600,600, 550,650, 550,650, 550,1600, 600,600, 600,1550, 650,600, 550,650, 550,1600, 600,600, 600,19800, 600,600, 600,600, 600,600, 600,600, 600,600, 600,600, 600,600, 550,650, 550,650, 550,600, 600,600, 600,600, 600,600, 600,600, 600,600, 600,600, 600,600, 600,600, 600,600, 550,650, 550,650, 550,600, 600,600, 600,600, 600,600, 600,1550, 650,600, 600,600, 550,650, 550,650, 550,600, 600,600, 600};  // GREE 8200040A
unsigned int  data = 0x8200040A;


I have been able to map the remote buttons using the AnalysisIR script and getting the raw info.

It works, but as raw values, the variables are much larger and I don't have space to map all the buttons.

**Comment by AnalysIR** [comment]
> It works, but as raw values, the variables are much larger and I don't have space to map all the buttons.

[Sending long AC Signals from Flash with IRremote](https://www.analysir.com/blog/2016/04/11/sending-long-ac-signals-flash-irremote/)

...and if that is not enough upgrade to an Arduino Mega2560 or clone ($<10 delivered)

**Comment by rcanoff** [comment]
@AnalysIR It worked using your example, I mapped about 20 raw codes and uploaded them to an Arduino UNO. 
Thank you.

**Comment by AbelHu** [comment]
@rcanoff Glad to know that it helps you. I updated examples/IRrecvDumpV2/IRrecvDumpV2.ino in this PR to print correct codes for GREE.

**Comment by onlysadegh** [comment]
@AbelHu Thanks for the efforts I tried your solution but couldn't get it to work , here is the report : 
Applying all the amendment in this PR to the library 
Receiving on ESP32 pin 15 with IRremote library example IRrecieveDumpV2 as follow : 
Encoding  : GREE
Code      : 92E1620A, C40004 (64 bits)
Timing[139]: 
     +8950, -4500     + 600, -1700     + 600, - 600     + 600, - 600
     + 650, -1650     + 600, - 600     + 650, - 550     + 650, -1650
     + 650, - 550     + 600, -1750     + 550, -1700     + 600, -1700
     + 600, - 600     + 600, - 600     + 600, - 650     + 550, - 650
     + 600, -1700     + 550, - 650     + 550, -1750     + 550, -1750
     + 550, - 650     + 600, - 600     + 600, - 600     + 600, -1700
     + 600, - 600     + 600, - 600     + 600, - 600     + 600, - 600
     + 600, - 600     + 600, -1700     + 600, - 600     + 600, -1700
     + 600, - 600     + 600, - 600     + 600, -1700     + 600, - 600
     + 600, -20050     + 600, -1700     + 600, - 600     + 600, - 600
     + 600, - 600     + 600, - 600     + 600, - 600     + 600, - 600
     + 600, - 600     + 600, -1700     + 600, -1700     + 600, - 600
     + 600, - 600     + 600, - 600     + 600, -1700     + 600, - 600
     + 650, - 550     + 600, - 600     + 600, - 600     + 650, - 550
     + 600, - 650     + 550, - 650     + 550, - 650     + 600, - 600
     + 600, - 600     + 600, - 600     + 600, - 600     + 600, - 600
     + 600, - 600     + 600, - 600     + 600, -1700     + 600, - 600
     + 600, - 600     + 600
unsigned int  rawData[139] = {8950,4500, 600,1700, 600,600, 600,600, 650,1650, 600,600, 650,550, 650,1650, 650,550, 600,1750, 550,1700, 600,1700, 600,600, 600,600, 600,650, 550,650, 600,1700, 550,650, 550,1750, 550,1750, 550,650, 600,600, 600,600, 600,1700, 600,600, 600,600, 600,600, 600,600, 600,600, 600,1700, 600,600, 600,1700, 600,600, 600,600, 600,1700, 600,600, 600,20050, 600,1700, 600,600, 600,600, 600,600, 600,600, 600,600, 600,600, 600,600, 600,1700, 600,1700, 600,600, 600,600, 600,600, 600,1700, 600,600, 650,550, 600,600, 600,600, 650,550, 600,650, 550,650, 550,650, 600,600, 600,600, 600,600, 600,600, 600,600, 600,600, 600,600, 600,1700, 600,600, 600,600, 600};  // GREE 92E1620A, C40004
unsigned int  data = 0x92E1620A, 0xC40004;

strangely two numbers and 64bits !!! , anyway I tried to send them individually through MEGA or UNO ( irsend.sendGREE (0x92E1620A or  0xC40004 , 32 or 64 ) )to the same ESP32 in order to test it , result on IRrecieveDumpV2  was different number and unknown protocol , what I am missing here 🔢

**Comment by AnalysIR** [comment]
@onlysadegh 

Your signal decodes as 67 bit electrolux on AnalysIR. (Name isn't important as it could also be a rebadged Gree etc)

It could also be that there are 3 fixed bits in the Gree implementation you are using, which would explain 64 vs 67 bits.

I would just use sendRAW to test the signal above first!  The signal capture itself looks pretty good.

**Comment by ArminJo** [comment]
Please rebase the code if the protocol is still required.
And it includes an incompatible redefinition of _GAP            20000

**Pull request closed without merging**
