### PR TITLE
Add support for Atmega16

### PR DESCRIPTION
**Pull request by amitesh-singh**

### CODE REVIEW

**Comment by amitesh-singh** [comment]
can someone please review a bit?

**Comment by amitesh-singh** [comment]
ping?

**Comment by q2dg** [comment]
Well...there is https://github.com/z3t0/Arduino-IRremote/pull/293 too

**Comment by z3t0** [comment]
Closing as #293 seems to cover it, please re open if there is anything extra in this addition. Thank you for the time and effort however! :smile:

**Pull request closed without merging**
