### PR TITLE
Add receiving support for Arduino 101

### PR DESCRIPTION
**Pull request by jimaobian**
Add receiving support for Arduino 101
Add F() in the serial print
Refine the macro define for esp32

### CODE REVIEW

**Comment by z3t0** [comment]
There has not been a formal review process setup for merging new additions to this project, but I think it would also be great if we could some confirmation that this also works for other users. Though again, I have no idea who from the community has access to the hardware (Arduino 101)

@jimaobian  thoughts?

**Comment by bengtmartensson** [comment]
This PR is not compatible with PR #437. Instead, it adds yet another C pre-processor symbol to the code proper (`IR_TIMER_USE_CURIE`) which was exactly the problem that #437 tried to address. 

#437 adds a "soft-carrier-send" which should make sending possible on all sufficiently fast boards, like the Curie.

**Comment by jimaobian** [comment]
@z3t0  Yes, I agree. This PR should be a hot patch for someone who would like to use IRRemote library on Arduino 101. It should be never merged but still exist until there are better implements.

@bengtmartensson Great! It is more elegant.  I'll do some review after #437 is merged into master.

**Comment by z3t0** [comment]
@jimaobian added to the readme

**Comment by jeffjvick** [comment]
Hi, I tested this 'hot patch' on an Arduino 101 and the receive appears to be working.  Unfortunately what I really need is to send.  

@jimaobian have you had any chance to look at what changes are needed on top of #437 to support this?  Is there any quick dirty way to send some NEC codes out?  I just need something hacky to get by.  Thanks.

**Comment by z3t0** [comment]
I created a beta release for #437 

If it is okay I would like to close this PR as a soft carrier has already been implemented in said PR.

**Comment by yygcom** [comment]
I need send , Oh my god

**Comment by bengtmartensson** [comment]
Suggest closing this PR. It is not compatible with the current code in master.

**Pull request closed without merging**
