### PR TITLE
Added support for ATmega8535, ATmega16 and ATmega32

### PR DESCRIPTION
**Pull request by MCUdude**
This pull request adds support for the ATmega8535, ATmega16 and ATmega32 using Timer 1 (tx = 13 with the standard pinout).

### CODE REVIEW

**Comment by z3t0** [comment]
Hi MCUdude! Thanks for the contribution, can I ask that you add the relevant information to the changelog? Thanks!

**Comment by z3t0** [comment]
#291

**Comment by MCUdude** [comment]
I certainly will :smile: 
About the list of compatible Arduinos/microcontrollers, what if you edited these lists so that all _boards_ where listed in one table, and all compatible _microcontrollers_ were listed in the other.

Another issue that may show of is the lack of information when choosing a microcontroller. You've listed the Sanguino, ATtiny84 and the ATtiny85. These are all great microcontrollers, but there are SO many cores to chose from, and most of them are old and outdated, and wouldn't work with Arduino IDE 1.6.x. What about making the names clickable, and directly be transferred to the "best" core available for that particular microcontroller?

**Comment by MCUdude** [comment]
If you want I can help you out here and add this to the pull request.

**Comment by z3t0** [comment]
> About the list of compatible Arduinos/microcontrollers, what if you edited these lists so that all boards where listed in one table, and all compatible microcontrollers were listed in the other.

That seems like a good idea

> Another issue that may show of is the lack of information when choosing a microcontroller. You've listed the Sanguino, ATtiny84 and the ATtiny85. These are all great microcontrollers, but there are SO many cores to chose from, and most of them are old and outdated, and wouldn't work with Arduino IDE 1.6.x. What about making the names clickable, and directly be transferred to the "best" core available for that particular microcontroller?

I'm not too sure what you mean by "core", sorry if I'm stupid but could you please explain this to me or even just link me to some documentation

**Comment by MCUdude** [comment]
A core is what you'll have to install in order to use microcontrollers that's not originally supported by the Arduino IDE. My core (MightyCore) adds support for a few more microcontrollers. Others are the core for Attiny84/85 ((ATtinyCore)) [https://github.com/SpenceKonde/ATTinyCore]

**Comment by z3t0** [comment]
@MCUdude ok thanks for explaining it and adding the relevant info in the readme. I will keep working on merging this but it will take a while for me to review all the changes as theres quite a lot to go through.

Thanks for the contribution!

**Comment by z3t0** [comment]
@MCUdude Please make this merge-able with master if possible as I would like to merge this asap.

**Comment by MCUdude** [comment]
How do I update my fork with your latest commits when I got a pull request active?

**Comment by z3t0** [comment]
Just commit the pull requests to your fork and I believe they will show up here. Thanks!

Will merge this as soon as it passes Travis.

**Comment by MCUdude** [comment]
Have a look at PR #324 instead

**Pull request closed without merging**
