### PR TITLE
Create IR2Keyboard.ino

### PR DESCRIPTION
**Pull request by pandacriss**
this is really useful to me. i think it will be for other users

### CODE REVIEW

**Comment by pandacriss** [comment]
oops. i was trying to add this to the examples folder. im not used to git.

**Comment by z3t0** [comment]
@pandacriss Could you add the relevant information to the changelog? Thanks!

**Comment by pandacriss** [comment]
ok i think i did. im not sure. im sorry, im  a noob with git

**Comment by z3t0** [comment]
If you want then maybe just explain the changes here and I can add it to the change log?

**Pull request merged**
