### PR TITLE
Added support for sending RC5x commands

### PR DESCRIPTION
**Pull request by mariusoei**
RC5x commands have a 2-cycle pause after the device ID, so they can't be
sent with the regular RC5 protocol.

This commit adds an sendRC5x function that accepts device ID, command and extension and sends the appropriate IR signal.

I have tested this with the modified IRRemote library for the ESP8266 and a Marantz amplifier.

This commit doesn't support decoding for RC5x because I don't have the means to test this.

See discussion at https://github.com/z3t0/Arduino-IRremote/issues/14

### CODE REVIEW

**Comment by nelu22** [comment]
Hello, can you help me with an sketch for send RC5X command. I want to learn an Marantz remote some commands.
Thankyou!

**Comment by mariusoei** [comment]
Yeah, what specifically do you need help with?

**Comment by nelu22** [comment]
When i try to use RC5x command in arduino i ghet error from compiler. I am not expert in programming .
Please help me with a little routine how to send one RC5x command on arduino.

**Comment by mariusoei** [comment]
Did you pull this branch? It's not pulled into the master branch yet.

**Comment by nelu22** [comment]
Thank you!

**Comment by mariusoei** [comment]
I believe I have been mistaken here. The RC5x-Protocol is different from what Marantz uses/used(?) in their devices. They seem to call it the "Marantz Extended Data Word", as described [here](http://lirc.10951.n7.nabble.com/Marantz-RC5-22-bits-Extend-Data-Word-possible-with-lircd-conf-semantic-td9784.html) and [here](https://sourceforge.net/p/lirc/mailman/lirc-list/thread/1361951809168-9801.post%40n7.nabble.com/#msg30537120).

I'm closing this pull request because what I implemented wasn't actually RC5x (which is now part of the library anyway).
I might open another one with the correct name at some point.

**Pull request closed without merging**
