### PR TITLE
Moving private includes to sub-directory,  #464

### PR DESCRIPTION
**Pull request by bengtmartensson**
This PM implements the sub-directories as discussed in the context of #464.

### CODE REVIEW

**Comment by bengtmartensson** [comment]
> Not much point in having paragraph if it's just a duplicate of sentence?

The reason that I added it was that the Arduino IDE (1.8.3) complained. (I started arduino from an xterm, if you start it by double clicking or something, it may happen that these warnings go into nirvana.) If "paragraph" is optional, then the IDE behaves incorrectly.

The best thing would probably be to add a "paragraph" (= several sentences) stating something more non-trivial.  Personally, I do not really care.

**Comment by z3t0** [comment]
That's odd, what about this then as the paragraph:

Arduino-IRremote has built in support for sending and decoding many IR signals.

**Comment by bengtmartensson** [comment]
I just revoked the change to library.properties, in order to keep the 1-1 correspondence to #464. (It was just a ugly warning that I wanted to kill.) After all, the warning does not hamper proper operation.

Still think that it should be fixed, though.

**Comment by z3t0** [comment]
> Still think that it should be fixed, though.

Could you open an issue with the warning output? That way we can explore this while also merging these changes.

**Pull request merged**
