### PR TITLE
New file MicroGirs.ino.

### PR DESCRIPTION
**Pull request by bengtmartensson**
Technically, this is another example file. 

The file MicroGirs.ino implements a minimal [Girs server](http://harctoolbox.org/Girs.html). After flashing  it on an Arduino with suitable sending- and/or receiving hardware, it can be used for IrScrutinizer and Lirc. This (sort-of...) eliminates the need for deploying another Arduino software (Infrared4Arduino, AGirs) for using Arduino with IrScrutinizer/Lirc.

The sketch can also be used as an interactive program for receiving and sending of raw IR signals.

Also see the comments in the file.

Cf. #449.

This PR does not depend on any other PR, and can be merged independently of the pending PRs.

### CODE REVIEW

**Comment by z3t0** [comment]
Note to self: rebate and merge

**Comment by ArminJo** [comment]
Hi, is it of further interest, or should we close this PR?

**Comment by bengtmartensson** [comment]
Yes, I still think it would be great. Give me a few days to update, though.

**Comment by ArminJo** [comment]
Thanks!

**Pull request merged**
