### PR TITLE
Add SAMSUNG to IRRecord.ino

### PR DESCRIPTION
**Pull request by Kruemmelspalter**
It wasn't included and said: "Unexpected codeType 7"

### CODE REVIEW

**Comment by ArminJo** [comment]
Are you aware that this repo is abandoned for 3 years?
Better try [IRMP](https://github.com/ukw100/IRMP) it icludes 50 protocols.

**Comment by Kruemmelspalter** [comment]
Oh... I didn't know that. I followed a tutorial and it said that I should use this

**Comment by AnalysIR** [comment]
@z3t0

**Comment by z3t0** [comment]
Merged.
@AnalysIR  thanks for the ping!

@Kruemmelspalter thank you for the fix! Much appreciated.

As for the status of this library, it is mostly unmaintained. However, I think most of the functionality is there and there aren't a lot of changes that make sense. The library is quite complete. We could continue adding protocols and support for more and more boards but I don't think that's particularly useful as users can do this by forking. We can't cover the use-cases of all users and there has been a lot of documentation through GitHub issues and external blogs which explain how to expand the library for more exotic uses. That said, I welcome patches and bug fixes and will always be happy to merge those in, assuming I see the patch, pinging me with @ is probably a good way to get my attention when its important and I seem unresponsive.

**Comment by ArminJo** [comment]
@z3t0 
Glad to hear from you.
Would it not be a good Idea to give e.g. @AnalysIR maintenance rights, to tag issues and close a few and maybe close some ancient and merge some sensible pull requests?
For every developer it is a great effort to browse through all the issues and pull requests and then looking to some forks, if his problem was solved there.

It is just an idea, but it could make programming life easier for some Arduino enthusiasts.

Best Regards
Armin

**Comment by z3t0** [comment]
Hi Armin, thank you for the suggestion.

I am definitely open and willing to add more users to the repository so that it can be governed and maintained without relying on me. As has been made clear by the state of this repo (sorry!) I haven't been very reliable here. 

I would prefer to add contributors that have a record of being involved within the Arduino-IRremote community and someone like @AnalysIR is perfect for that. If they are willing then I would be happy to make that happen. Let me know!

**Comment by ArminJo** [comment]
Hi @AnalysIR,
I would very much appreciate, if you are willing to put some effort in maintaining this repository.
Also for me you are the perfect person for this 🥇 .
If you like,I can support you by e.g. closing issues and [testing pull requests](https://github.com/sparkfun/SparkFun_VL53L1X_Arduino_Library/actions/runs/110823504).

**Make us happy!**

Armin

**Comment by AnalysIR** [comment]
@z3t0 As previusly discussed, I am not in a position to do this, as our AnalysIR software applications and  IR hardware modules take priority for us, in addition to the other reasons I provided at the time. However, I will continue to provide end-user support here when possible.

_In the future we may create an IRremote fork dedicated to our recently launched [KontroLIR ](https://www.analysir.com/blog/product/kontrolir-arduino-compatible-ir-remote-control/)remote control, but so far it has not been neccessary as IRremote functions very well indeed. We also plan to release a version of our LearnIR V2 hardware (i.e. USB Dongle) which runs IRremote.(instead of LearnIR)_

**Comment by z3t0** [comment]
@AnalysIR Absolutely completely understood, thank you for your continuing support for the community.

@ArminJo If you are interested feel free to help clean up issues and PRs. I think for the most part a lot of the issues are really feature requests or supports for help, few are bugs. And for the PRs a lot of them are really out of the scope of this library.

If you would be interested I can look into adding you as a maintainer of the repo and then you should be able to close/open issues and add labels etc. The only concern I have is that I don't see this library as needed much more development. Bug fixes and cleaning up are okay, but otherwise I tend to see the library as "complete". If your opinions on that differ then we can certainly discuss and try to come up with a vision for this library that is more suited to the community!

**Comment by z3t0** [comment]
Also this discussion may be more appropriate in #525

**Pull request merged**
