### PR TITLE
MagiQuest and 3.5ch Helicopters

### PR DESCRIPTION
**Pull request by mpflaga**
I have added support for MagiQuest Wands, along with support for inexpensive 3.5ch Helicopters. With an additional example IRsendDemoHelicopter that emulates the multi-channel remote. And harmonized the types to c99 for consistency.
Have fun.

### CODE REVIEW

**Comment by z3t0** [comment]
Anyone, feel free to rebase off master.. will get to it eventually

**Comment by kitlaan** [comment]
FYI, I've reimplemented the original code off the latest master at kitlaan/Arduino-IRremote@df0eed9ef92bcb3cb108612e134e3a4716409180

It's not quite the same, but functionally equivalent.

**Comment by pcoughlin** [comment]
@kitlaan ... What are the differences with your re-implementation?

**Comment by z3t0** [comment]
@mpflaga Please check as there seem to be merge conflicts.

**Comment by kitlaan** [comment]
@pcoughlin, currently just the receive code per the "new" code format, in a cleaner manner.  (Since the MagiQuest protocol is more PWM than mark/space, the code follows that.)

If you want, I can trigger a brand new pull request once I implement send(), unless you want this as-is.

**Comment by trevmex** [comment]
I can verify that kitlaan's code (https://github.com/kitlaan/Arduino-IRremote/commit/df0eed9ef92bcb3cb108612e134e3a4716409180) does work with the current MagiQuest wands.

**Comment by ArminJo** [comment]
Hi, is it of further interest, or should we close this PR?

**Comment by mpflaga** [comment]
no long familiar with project to provide any response

**Pull request closed without merging**
