### PR TITLE
Add bosewaveradio support

### PR DESCRIPTION
**Pull request by uvotguy**
Add support for a Bose Wave Radio CD player.

I had no luck in finding a spec for the Bose protocol; however, I have a working remote and player.
 I believe the IR LED in my remote is getting weak - iIt only works at close range even with a fresh battery.  I wanted to make my own remote control before it died, so here I am!

I captured signals from each button with a simple TSOP38238 IR Receiver Module (a.k.a. phototransistor) and an oscilloscope.  Once I got the protocol down, I captured a number of signals and averaged the timing for the relevant waveform components.

My new Arduino based remote works well even at a distance.

FYI I'm new at this Open Source thing, so please let me know if I've stepped on any toes, or if something can be improved.

### CODE REVIEW

**Comment by ArminJo** [comment]
Just one question.
Why did you not find/use the BOSE protocol [here](https://github.com/ukw100/IRMP#list-of-protocols)?

**Comment by uvotguy** [comment]
Thanks for the reply, @ArminJo.  I wasn't aware of IRMP.  LIRC came up in my search, but the timing didn't match my measurements.  Your m'ments match mine nicely.  Since IRMP dev is more active, I'll give it a try.  Thanks!

Quick question for you. Was your timing done empirically, or did you work from a spec?

**Comment by ArminJo** [comment]
I guess the timing was done empirical, I am not the developer of the software.
If you have problems with IRMP do not hesitate to open an issue there 😀 .

BTW your code seems quite clean, so maybe it will be merged later.

**Comment by uvotguy** [comment]
Thank you.  I always try to emulate the project style.  I hope somebody can find use for it if they're wed to IRremote.

Can't wait to try IRMP!!!!

**Pull request merged**
