### PR TITLE
Added support for RC5 extended

### PR DESCRIPTION
**Pull request by LarsWH**
Hi,

I added support for 'RC5 extended' in order to make this project: https://www.instructables.com/id/Remote-Control-for-Lava-mMotion-Swing-Mounting-Bra/

The modification is working nicely in this single application. It has not been tested elsewhere.

(I am new to Git and this is my first pull request ever. So please excuse me if I have messed something up)

Kind regards,
Lars

### CODE REVIEW

**Comment by z3t0** [comment]
Everything seems to have been done excellently. Are you sure it's the first time you have used git :smile:

For the sake of being verbose might I request you add a small description of your changes to changelog.md and then push that commit upstream? I will merge once that has been added.

**Comment by LarsWH** [comment]
Hi Rafi,
I have added a one-liner to changelog.md and pushed it.
I have only been using Git as a single-user thing, and most of the time only locally on my computer. This is indeed my first time to make a pull-request. Fingers crossed...

**Comment by AnalysIR** [comment]
@z3t0 
some comment based on a very short/incomplete review

```
ir_NEC.cpp
delay(200);  // Added by LWH
```

That is a significant delay to introduce before sending a signal. IS there  a good reason for it?

```
irRC5_RC6.cpp
#define RC5_T1             830 //LWH originally: 889
```

The original value is correct (830 is not RC5)

`void  disableIROut 		( ) ;`

Not sure of the rationale for this? What is it?


Finally, is there a case to be made that `sendRC6ext` could make use of `sendRC5 `to achieve the same result with less flash memory used up. (Just generate the parameters required by `sendRC5 `in `sendRC6ext`

**Comment by LarsWH** [comment]
Are those changes really in the head version? Then I really did mess up   :-(
The head version should ONLY contain changes to ir_RC5_RC6. and IRremote.h.
The other things comes from experiments (an Arduino that is receiving from a Sony remote control and passing on signals to a Nec and RC5 devices).
It is a bit late here in Denmark, but tomorrow I will try to figure out how I messed up my head revision.

**Comment by LarsWH** [comment]
@AnalysIR @z3t0  I have verified that the changes from Rafi’s latest version (741d9e, September 10) to my latest version (ddac72, September 19, see screen dump) does not contain any of the experimental stuff you listed. Can you please double check you are seeing the same? 

I did joggle around with a few branches, doing experiments for that other project I mentioned, but those hacks should be all gone now. Those experimental branches/commits should really not have been visible to others, but obviously I have not yet fully understood the Git flow. My apologies.

image

**Comment by AnalysIR** [comment]
FI: I just clicked on the links earlier in this thread, to find the code...otherwise I'll leave it to @z3t0 to figure it all out :)

> New changes since you last viewed
> LarsWH added some commits 8 days ago

**Comment by z3t0** [comment]
It all looks good on my side. Will merge after bumping the version number

**Comment by z3t0** [comment]
Awaiting for the checks to finish on the other branch. Will merge after.

**Comment by z3t0** [comment]
@LarsWH This has just been merged onto beta. Will mark it as such and close this PR once it makes it onto a release.

**Comment by LarsWH** [comment]
@z3t0  Thank you for accepting my enhancements into your excellent library :-)

**Comment by ArminJo** [comment]
Included in 2.5.0

**Pull request closed without merging**
