### PR TITLE
Fix calculation of pause length in LEGO PF protocol

### LINKED ISSUE #384: Interger overflow in LEGO Power Functions
**Board:** ARDUINO UNO
**Library Version:** master (7c14514beb586e2d55942838bae087d1d930308b)

**Compiler warning**
```
In file included from /Arduino/libraries/IRremote/ir_Lego_PF.cpp:3:0:
/Arduino/libraries/IRremote/ir_Lego_PF_BitStreamEncoder.h: In member function 'int LegoPfBitStreamEncoder::getRepeatStopPause() const':
/Arduino/libraries/IRremote/ir_Lego_PF_BitStreamEncoder.h:107:38: warning: integer overflow in expression [-Woverflow]
       return STOP_PAUSE_DURATION + 5 * MAX_MESSAGE_LENGTH - messageLength;
                                      ^
```
The returned value is 65026, but the Arduino UNO's signed integer maximum value is 32767.

### PR DESCRIPTION
**Pull request by henkel**
Fix #384 Interger overflow in LEGO Power Functions affects pause
between messages

### CODE REVIEW

**Comment by henkel** [comment]
@z3t0 Please consider the merge for this PR in the christmas break #386

I'm also ready to adapt the implementation of the Lego Power Function protocol to your new structure and would love to see testability taken into account. Let me know when I can support or provide feedback.

**Comment by henkel** [comment]
@z3t0 Please merge this bug fix. It only affects the the LEGO protocol implementation and tests.

**Comment by z3t0** [comment]
@henkel I am ready to merge this, can you please take a look at rebasing it off master? There have been recent commits that offset this PR

**Comment by henkel** [comment]
@z3t0 I merged master and github says "this pull request can be automatically merged". Does that work for you?

**Comment by z3t0** [comment]
It seems to be locked on my end. I'll close this PR from my end, and then could you recreate it? It seems that the compulsory status checks are frozen and I'm not sure how to force restart them...

**Comment by philipphenkel** [comment]
Ooops, I missed the close notification. I will re-create the PR based on master.

**Pull request closed without merging**
