### PR TITLE
Add Lego Power Functions Receiver.

### PR DESCRIPTION
**Pull request by mwinters-stuff**
Adds the Lego Power Functions IR Protocol Receiver.

### CODE REVIEW

**Comment by AnalysIR** [comment]
I suggest you rename your defines and functions to include some identification of the device

e.g DECODE_POWERFUNCTIONS
could refer to any device & does not tell other users which device this is for & may make future debugging difficult.

**Comment by wintersandroid** [comment]
Hi.
Changed the defines and function names.. Should be a bit less "confusing" now.. :)

**Comment by z3t0** [comment]
I will add the necessary info in the changelog and merge this once I get a chance, if possible can you list the changes in the changelog yourself? to speed things up, otherwise I will definitely get to it albeit eventually.

**Comment by nwegner** [comment]
Has to be synced with PR#309 already providing Lego Power Functions send functionality

**Comment by ArminJo** [comment]
Manually added for version 2.8.0

**Pull request closed without merging**
