### PR TITLE
Add Lego Power Functions tests

### PR DESCRIPTION
**Pull request by henkel**
I moved the BitStreamEncoder code to a separate header file in order to allow basic unit testing with a dedicated test sketch.

### CODE REVIEW

**Comment by z3t0** [comment]
This will be put on hold while we figure things out at #333

**Comment by henkel** [comment]
BitStreamEncoder is actually a protocol implementation that plugs into a simple, straight forward IRsend send function. I'm sure whatever the outcome of #333 is, the Lego Power Functions part can be easily adapted to match the new structure. Let me know when you are ready.

```
    bitStreamEncoder.reset(data, repeat);
    do {
      mark(bitStreamEncoder.getMarkDuration());
      space(bitStreamEncoder.getPauseDuration());
    } while (bitStreamEncoder.next());
```

**Comment by z3t0** [comment]
In that case, I might as well implement this as it may be a while until we have #333 sorted out, if possible please check and update the PR against master as I just merged another PR so that would have offset your commits

**Comment by henkel** [comment]
@z3t0 I updated against master. The PR is ready to be merged.

**Comment by z3t0** [comment]
Looks good, just one more thing, please add your changes to the changelog and just bump the version

**Comment by henkel** [comment]
@z3t0 Changelog and versions are up-to-date now

**Comment by z3t0** [comment]
Thank you for your efforts! and I apologize for not helping out with the merge.

**Pull request merged**
